---
# Install latest docker
# https://docs.docker.com/engine/install/ubuntu/

- name: 'Older versions of Docker were called docker, docker.io, or docker-engine. If these are installed, uninstall them:'
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: 'Update the apt package index and install packages to allow apt to use a repository over HTTPS:Older versions of Docker were called docker, docker.io, or docker-engine. If these are installed, uninstall them'
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
    state: present
  become: true

- name: 'Add docker official pgp key'
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: 'Get Ubuntu version name'
  ansible.builtin.shell:
    cmd: echo $(lsb_release -cs)
  register: lsb_name

- name: 'Get architecture'
  ansible.builtin.shell:
    cmd: echo $(dpkg --print-architecture)
  register: architecture

- name: 'Debug'
  debug:
    msg: 'lsb: {{lsb_name.stdout}}, arch: {{architecture.stdout}}'

- name: 'Add source repository into sources list'
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{architecture.stdout}}] https://download.docker.com/linux/ubuntu {{lsb_name.stdout}} stable'
    state: present
  become: true

- name: 'Update apt-cache and install docker'
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
  become: true
