BOX_IMAGE = "ubuntu/focal64"

SERVER_DC1_NODES = 1
SERVER_DC2_NODES = 0

CLIENT_DC1_NODES = 1
CLIENT_DC2_NODES = 1

BRIDGE_NETWORK_INTERFACE_NAME = "Realtek 8821CE Wireless LAN 802.11ac PCI-E NIC"

Vagrant.configure("2") do |config|

  config.vm.define "nj1.local.jumper.nomad" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nj1-local-jumper-nomad"
    subconfig.vm.network "private_network", ip: "10.0.1.2"
    subconfig.vm.network "public_network", bridge: BRIDGE_NETWORK_INTERFACE_NAME
    subconfig.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  # Server nodes
  ## DC1 Server nodes
  IP_OFFSET = 2
  (1..SERVER_DC1_NODES).each do |i|
    config.vm.define "ns#{i}.dc1.server.nomad" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "ns#{i}-dc1-server-nomad"
      subconfig.vm.network "private_network", ip: "10.0.1.#{i+IP_OFFSET}"
      subconfig.vm.network "public_network", bridge: BRIDGE_NETWORK_INTERFACE_NAME
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end

  ## DC2 Server nodes
  IP_OFFSET = 2 + SERVER_DC1_NODES
  (1..SERVER_DC2_NODES).each do |i|
    config.vm.define "ns#{i}.dc2.server.nomad" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "ns#{i}-dc2-server-nomad"
      subconfig.vm.network "private_network", ip: "10.0.1.#{i+IP_OFFSET}"
      subconfig.vm.network "public_network", bridge: BRIDGE_NETWORK_INTERFACE_NAME
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end

  # Client nodes
  ## Client DC1 nodes
  IP_OFFSET = 2 + SERVER_DC1_NODES + SERVER_DC2_NODES
  (1..CLIENT_DC1_NODES).each do |i|
    config.vm.define "nc#{i}.dc1.client.nomad" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "nc#{i}-dc1-client-nomad"
      subconfig.vm.network "private_network", ip: "10.0.1.#{i+IP_OFFSET}"
      subconfig.vm.network "public_network", bridge: BRIDGE_NETWORK_INTERFACE_NAME
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end
  
  ## Client DC2 nodes
  IP_OFFSET = 2 + SERVER_DC1_NODES + SERVER_DC2_NODES + CLIENT_DC1_NODES
  (1..CLIENT_DC1_NODES).each do |i|
    config.vm.define "nc#{i}.dc2.client.nomad" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "nc#{i}-dc2-client-nomad"
      subconfig.vm.network "private_network", ip: "10.0.1.#{i+IP_OFFSET}"
      subconfig.vm.network "public_network", bridge: BRIDGE_NETWORK_INTERFACE_NAME
      subconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end
end