# Helping links
#
# special_variables: https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
#

---
- name: 'Setup all given server from the inventory file'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Install nomad on all machines'
      include_role:
        name: 'install_nomad'

    - name: 'Install docker on all client machines'
      include_role:
        name: 'install_docker'
      when: '"nomadclients" in group_names'

    - name: 'Configures nomad server by creating a server cluster'
      include_role:
        name: 'configure_nomad_server'
      when: '"nomadserver" in group_names'

    - name: 'Configures nomad client setting nomad as a service and configureing as client'
      include_role:
        name: 'configure_nomad_client'
      when: '"nomadclients" in group_names'

    # TODO: Configures nomand clients to connect to server cluster
