---
- name: TestPlay
  hosts: jumpservers
  become: yes
  gather_facts: yes

  tasks:
    - name: "Add an Apt signing key, uses whichever key is at the URL"
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: "Get Ubuntu version name"
      ansible.builtin.shell:
        cmd: echo $(lsb_release -cs)
      register: lsb_name

    - name: "Debug {{lsb_name.stdout}}"
      debug:
        msg: "Lsb name {{lsb_name.stdout}}"

    - name: "Add source repository into sources list"
      ansible.builtin.apt_repository:
        repo: deb-src https://apt.releases.hashicorp.com {{lsb_name.stdout}} main
        state: present

    - name: "Update apt-cache and install nomad"
      apt:
        name: nomad
        update_cache: yes
