BOX_IMAGE = "ubuntu/focal64"
DC1_NODE_COUNT = 2
DC2_NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "jumpserver" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "nomad.local.nj1.jumpserver"
    subconfig.vm.network :private_network, ip: "10.0.1.1"
  end
  
  (1..DC1_NODE_COUNT).each do |i|
    config.vm.define "dc1.worker#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "nomad.dc1.vm#{i}.worker"
      subconfig.vm.network :private_network, ip: "10.0.1.#{1+i}"
    end
  end

  (1..DC2_NODE_COUNT).each do |i|
    config.vm.define "dc2.worker#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "nomad.dc2.vm#{i}.worker"
      subconfig.vm.network :private_network, ip: "10.0.1.#{1+DC1_NODE_COUNT+i}"
    end
  end
end
